# Generated by Django 5.1 on 2026-07-07 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='games_drawn',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='games_lost',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='games_won',
        ),
    ]
