# Generated by Django 5.1 on 2026-07-17 11:54

import apps.games.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('local', 'Local (pass and play)'), ('engine', 'vs Computer'), ('online', 'Online Multiplayer')], max_length=10)),
                ('result', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw')], max_length=4)),
                ('termination', models.CharField(choices=[('checkmate', 'Checkmate'), ('stalemate', 'Stalemate'), ('timeout', 'Timeout'), ('resignation', 'Resignation')], default='checkmate', max_length=12)),
                ('engine_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('time_control_initial', models.PositiveIntegerField(blank=True, null=True)),
                ('time_control_increment', models.PositiveIntegerField(default=0)),
                ('moves', models.JSONField(blank=True, default=list)),
                ('total_moves', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'games',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnlineGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(default=apps.games.models.generate_room_code, max_length=8, unique=True)),
                ('fen', models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', max_length=100)),
                ('status', models.CharField(default='waiting', max_length=20)),
                ('winner', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('black_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_black', to=settings.AUTH_USER_MODEL)),
                ('white_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_white', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
