# Generated by Django 5.1 on 2026-07-12 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('local', 'Local (pass and play)'), ('engine', 'vs Computer')], max_length=10)),
                ('result', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw')], max_length=4)),
                ('termination', models.CharField(choices=[('checkmate', 'Checkmate'), ('stalemate', 'Stalemate'), ('timeout', 'Timeout'), ('resignation', 'Resignation')], default='checkmate', max_length=12)),
                ('engine_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('time_control_initial', models.PositiveIntegerField(blank=True, null=True)),
                ('time_control_increment', models.PositiveIntegerField(default=0)),
                ('moves', models.JSONField(blank=True, default=list)),
                ('total_moves', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'games',
                'ordering': ['-created_at'],
            },
        ),
    ]
