# Generated by Django 5.1 on 2026-07-07 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=1200),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('LOCAL', 'Local'), ('AI', 'AI'), ('ONLINE', 'Online')], default='LOCAL', max_length=10)),
                ('status', models.CharField(choices=[('ONGOING', 'Ongoing'), ('FINISHED', 'Finished'), ('ABANDONED', 'Abandoned')], default='ONGOING', max_length=10)),
                ('termination', models.CharField(blank=True, choices=[('CHECKMATE', 'Checkmate'), ('STALEMATE', 'Stalemate'), ('RESIGNATION', 'Resignation'), ('TIMEOUT', 'Timeout'), ('DRAW', 'Draw')], max_length=20, null=True)),
                ('moves', models.JSONField(default=list)),
                ('move_count', models.PositiveIntegerField(default=0)),
                ('initial_fen', models.TextField(default='startpos')),
                ('final_fen', models.TextField(blank=True, null=True)),
                ('time_control', models.IntegerField(default=600)),
                ('increment', models.IntegerField(default=0)),
                ('white_time_remaining', models.IntegerField(blank=True, null=True)),
                ('black_time_remaining', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('black_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='black_games', to=settings.AUTH_USER_MODEL)),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_games', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_won_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
