# Generated by Django 5.1 on 2026-07-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game'),
        ('games', '0002_onlinegame'),
    ]

    operations = [
    ]
